export const DEFAULT_SCENES_PER_PAGE = 100
export const DEFAULT_SCENE_CHUNK_SIZE = 250
export const DEFAULT_UPDATE_CONCURRENCY = 10
export const DEFAULT_HASH_BATCH_SIZE = 2000
export const DEFAULT_MAX_PAGES_PER_SOURCE = 100
